
- name: Setup git
  hosts: jenkins
  become: yes
  tasks:
    - name: Install git
      apt: name=git state=present

- name: Setup Terraform
  hosts: jenkins
  become: yes
  tasks:
    - name: Ensure unzip is installed
      apt: name=unzip state=present
    - name: Check for presence of terraform
      ignore_errors: True     # rc != 0 is okay, indicates program not existing
      command: which terraform
      register: which_result
      changed_when: which_result.rc != 0     # Show changed when terraform is missing
    - name: Download + Unpack Terraform
      unarchive: src=https://releases.hashicorp.com/terraform/0.6.15/terraform_0.6.15_linux_amd64.zip dest=/usr/local/bin copy=no
      when: which_result.rc != 0

- name: Put AWS credentials on machine
  hosts: jenkins
  remote_user: jenkins
  become: yes
  tasks:
    - name: Include encrypted credentials
      include_vars: vars.yml
    - name: Create .aws directory
      file: path=/var/lib/jenkins/.aws state=directory
    - name: Copy credentials
      copy: content={{ aws_credential_file_content }} dest=/var/lib/jenkins/.aws/credentials


- name: Setup Jenkins
  hosts: jenkins
  become: yes
  tasks:
  - name: Ensure Jenkins' key is added to apt
    apt_key: url=https://jenkins-ci.org/debian/jenkins-ci.org.key state=present
  - name: Ensure Jenkins repo is added to apt
    apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present
  - name: Ensure Jenkins package is installed
    apt: name=jenkins state=present update_cache=yes
  - name: Read initial admin password
    command: /bin/bash -c 'cat /var/lib/jenkins/secrets/initialAdminPassword || echo "N/A"'
    register: cat_result    # Make result (including output, return code available as a variable)
    changed_when: cat_result.stdout != "N/A"    # This step only says "changed" when it's an initial deployment
  - name: Print hostname (on initial-provisioning
    debug: msg="Jenkins on {{inventory_hostname}} is done! Go to {{ansible_nodename}} and enter {{admin_pw.stdout}}"
    when: cat_result.stdout != "N/A"    # Only print debug message on initial deployments - otherwise it's unneeded and the PW is "N/A"
