info:
  component: Appointment Request Scheduler

server:
  port: 0
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5

#tmp
incomingAppointmentQueue: appointmentRequestQueue
slotFoundQueue: slotFoundQueue
noSlotFoundQueue: noSlotFoundQueue
incomingAppointmentQueueHost: localhost


---

spring:
    profiles: docker

eureka:
  client:
      serviceUrl:
        defaultZone: http://discoveryservice:8761/eureka/

incomingAppointmentQueueHost: theRabbit
