env:
  - TERM=dumb

jdk:
  - oraclejdk8

script: ./applications/buildAll.sh clean build

addons:
  artifacts: true
  paths:
    - applications/supportingServices/discoveryService
    - applications/supportingServices/mcrs-config
    - applications/supportingServices/edgeService
    - applications/appointmentGateway
    - applications/theProducer
    - applications/appointmentRequestScheduler
    - applications/statusService
  debug: true
  
notifications:
  slack: zuehlke:kDdWfWR1yjyNvVJeAVkrasHn
