#%RAML 0.8
title: CatCalZone API
baseUri: http://catcal.zone/
version: v1
mediaType: application/json
schemas:
    - appointmentRequest: |
        {
              "type": "object",
              "$schema": "http://json-schema.org/draft-03/schema",
              "id": "http://jsonschema.net",
              "required": true,
              "properties": {
                    "requestUser": {
                        "type" : "string",
                        "items": {
                            "type": "string"
                        },
                        "minItems": 1,
                        "uniqueItems": true,
                        "required" : true
                    },
                    "attendees": {
                        "type" : "array",
                        "required" : true
                    },
                    "minStartDate": {
                        "type" : "date",
                        "required" : true
                    },
                    "maxEndDate": {
                        "type" : "date",
                        "required" : true
                    },
                    "durationInHours": {
                        "type" : "integer",
                        "required" : true
                    },
                    "title": {
                        "type": "string",
                        "required": true
                    }

              }
        }
/:
  get:
    description: Depending on the requested mediatype returns this document or a HTML version of it
    responses:
        200:
            body:
                text/html:
                application/raml+yaml:
/appointmentRequest:
  get:
    description: Returns a list of appointment requests for a user
    queryParameters:
        user:
            required: true
    #responses: TODO
  post:
    description: Inserts a new appointment request
    body:
        application/json:
            schema: appointmentRequest
            example: TODO
  /{appointmentRequestId}:
    get:
        description: Returns a specific request by ID.
    put:
        description: Updates an appointment request
    delete:
        description: Cancles a specific request by ID.
  /slot/{appointmentSlotId}:
    get:
        description: Returns a specific slot by id.
    put:
        description: Updates a specific slot by id