info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "/**"
  routes:
    appointmentGateway:
      path: /appointment/**
      method: POST
      stripPrefix: false
    statusService:
          path: /appointment/**
          method: GET
          stripPrefix: false

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

eureka:
   instance:
    # hostname:
      leaseRenewalIntervalInSeconds: 10
      metadataMap:
        instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
   client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

---

spring:
    profiles: docker

eureka:
  client:
      serviceUrl:
        defaultZone: http://discoveryservice:8761/eureka/

