spring:
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    searchLocations: src/main/resources/configTmp
server:
  port: 8888
