info:
  component: Appointment Request Status Service

server:
  port: 0
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
       defaultZone: http://localhost:8761/eureka/

incomingAppointmentQueue: appointmentRequestQueue
incomingAppointmentQueueHost: localhost

---

spring:
    profiles: docker

eureka:
  client:
      serviceUrl:
        defaultZone: http://discoveryservice:8761/eureka/

incomingAppointmentQueueHost: theRabbit


---

spring:
    profiles: mock
server:
  port: 8082