Vagrant.configure("2") do |config|
  config.vm.box = "chef/ubuntu-14.04"
  config.vm.synced_folder "../applications", "/applications", create: true
 # config.vm.network "forwarded_port", guest: 8090, host: 8090 # appointmentGateway
 # config.vm.network "forwarded_port", guest: 8087, host: 8087 # theProducer
  config.vm.network "forwarded_port", guest: 8761, host: 8761 # Eureka server
  config.vm.network "forwarded_port", guest: 8888, host: 8888 # config server
  config.vm.network "forwarded_port", guest: 9324, host: 9324 # elasticMQ

  config.vm.provider "virtualbox" do |v|
    v.memory = 3092
    v.cpus = 2
  end
  
  config.vm.provision "docker" do |d|    
    d.build_image "--tag=eureka /vagrant/eureka"
    d.build_image "--tag=configsrv /vagrant/configsrv"
    d.build_image "--tag=elasticmq /vagrant/elasticMQ" 

    d.run "eureka",
      args: "-p 8761:8761 -v /applications:/applications"
   # d.run "configsrv",
   #   args: "-p 8888:8888 -v /applications:/applications"

    d.run "elasticmq",
      args: "-p 9324:9324 -v /vagrant:/vagrant"

  end

end
